project:
  type: website
  output-dir: docs

website:
  title: "Math 437 Website"
  navbar:
    background: 'mediumpurple'
    fontcolor: 'lavender'
    left:
      - href: index.qmd
        text: Home
      - Final Project.qmd

format:
  html:
    backgroundcolor: 'lavender'
    fontcolor: '#330066'
    linkcolor: 'mediumpurple'
    theme: cosmo
    css: styles.css
    toc: true



